[package]
name = "trussed"
version = "0.1.0"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
repository = "https://github.com/trussed-dev/trussed"
license = "Apache-2.0 OR MIT"
description = "Modern Cryptographic Firmware"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
# Testing
serial_test = { version = "*" }
entropy = "0.3.0"
rand_core = { version = "0.5.1", features = ["getrandom"] }

[dependencies]
aes = { version = "0.3.2", default-features = false }
block-modes = { version = "0.3.3", default-features = false }
block-cipher-trait = { version = "0.6.2" }
chacha20 = { version = "0.3.4", features = ["rng"] }
chacha20poly1305 = { version = "0.3.3", default-features = false, features = ["heapless", "reduced-round"] }
cosey = "0.1.0"
delog = "0.1.0-alpha.3"
rand_core = "0.5.1"
cbor-smol = "0.1.0"
des = { version = "0.3.0", optional = true }
embedded-hal = { version = "0.2.3", features = ["unproven"] }
generic-array = "0.12.3"  # "0.13.2"
# generic-array = "0.13.2"
# generic-array = { version = "0.13.2", default-features = false }
heapless = { version = "0.5.6", features = ["serde"] }
# heapless = { git = "https://github.com/nickray/heapless", branch = "heapless-14" }
heapless-bytes = { version = "0.1.0", features = ["cbor"] }
hmac = "0.7.1"
interchange = "0.1.2"
littlefs2 = "0.1.0"
nb = "1"
serde = { version = "1.0", default-features = false }
serde_cbor = { version = "0.11.0", default-features = false }
serde-indexed = "0.1.0"
sha-1 = { version = "0.8.2", default-features = false, optional = true }
sha2 = { version = "0.8.0", default-features = false }


[dependencies.nisty]
version = "0.1.0-alpha.3"
features = ["asn1-der", "cose"]

[dependencies.salty]
git = "https://github.com/ycrypto/salty"
branch = "main"
features = ["cose"]

[features]
default = ["default-mechanisms"]
verbose-tests = ["littlefs2/ll-assertions"]
verbose-lfs = ["littlefs2/ll-assertions", "littlefs2/ll-trace"]

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

# mechanisms
# default-mechanisms = ["aes256-cbc", "chacha8-poly1305", "ed255", "hmac-sha256", "p256", "sha256", "trng"]
default-mechanisms = [
    "aes256-cbc",
    "chacha8-poly1305",
    "ed255",
    "x255",
    "hmac-sha256",
    "p256",
    "sha256",
    "tdes",
    "totp",
    "trng",
]
aes256-cbc = []
chacha8-poly1305 = []
ed255 = []
x255 = []
hmac-sha256 = []
p256 = []
sha256 = []
tdes = ["des"]
totp = ["sha-1"]
trng = ["sha-1"]

clients-2 = []
clients-3 = []
clients-4 = []
clients-5 = []
clients-6 = []
clients-7 = []
clients-8 = []
clients-9 = []
clients-10 = []
clients-11 = []
clients-12 = []

# [patch.crates-io]
# interchange = { git = "https://github.com/trussed-dev/interchange", branch = "main" }
