name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: >
          sudo apt-get update -y -qq &&
          sudo apt-get install -y -qq llvm libc6-dev-i386 libclang-dev
      - uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: "9-2020-q2"
      - name: Build
        run: cargo build --verbose --features clients-1
      - name: Run tests
        run: cargo test --verbose --features clients-12

      - name: Build Documentation
        run: cargo doc --no-deps --features clients-1
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
